# Generated by Django 5.1.7 on 2025-12-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_type', models.CharField(choices=[('warehouse_to_driver', 'Warehouse → Driver'), ('driver_to_warehouse', 'Driver → Warehouse'), ('driver_to_station', 'Driver → Pickup Station'), ('station_to_courier', 'Station → Courier'), ('courier_to_customer', 'Courier → Customer'), ('return_to_station', 'Return → Pickup Station'), ('return_to_warehouse', 'Return → Warehouse'), ('inter_warehouse', 'Warehouse → Warehouse')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_ack', models.BooleanField(default=False)),
                ('to_ack', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_code', models.CharField(blank=True, max_length=10)),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('guest_id', models.CharField(blank=True, max_length=50)),
                ('signed_off', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('delivery_refused', 'Customer refused delivery'), ('customer_unavailable', 'Customer not available'), ('wrong_address', 'Wrong address provided'), ('expired_window', 'Exceeded pickup window'), ('damaged_in_transit', 'Damaged in transit'), ('expired', 'Expired goods'), ('packaging_issue', 'Packaging issue'), ('failed_delivery_attempt', 'Failed delivery attempts'), ('restricted_item', 'Restricted item'), ('lost_in_transit', 'Lost in transit'), ('customer_requested_return', 'Return to sender requested')], default='failed_delivery_attempt', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('home_delivery_location', models.TextField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('fragile', models.BooleanField(default=False)),
                ('requires_signature', models.BooleanField(default=False)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('overnight', 'Overnight')], default='standard', max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('online', 'Online Payment'), ('pickup', 'Pay on Pickup'), ('none', 'Unpaid')], default='none', max_length=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('packed', 'Packed'), ('in_transit', 'In Transit'), ('at_station', 'At Pickup Station'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned_station', 'Returned to Pickup Station'), ('returned_warehouse', 'Returned to Warehouse'), ('cancelled', 'Cancelled')], default='packed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('destination_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='locations.location')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='locations.location')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_parcels', to='customers.customer')),
                ('sender_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_parcels', to='customers.customer')),
                ('sender_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_parcels', to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelExcange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('from_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches_from', to='customers.customer')),
                ('from_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches_from', to='locations.location')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='parcels.parcel')),
            ],
        ),
    ]
