# Generated by Django 5.1.7 on 2025-12-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('locations', '0002_initial'),
        ('parcels', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelexcange',
            name='switched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='parcelexcange',
            name='to_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches_to', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='parcelexcange',
            name='to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches_to', to='locations.location'),
        ),
        migrations.AddField(
            model_name='parcelhandover',
            name='from_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_from', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='parcelhandover',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='locations.location'),
        ),
        migrations.AddField(
            model_name='parcelhandover',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='parcels.parcel'),
        ),
        migrations.AddField(
            model_name='parcelhandover',
            name='to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_customer', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='parcelhandover',
            name='to_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_to', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='parcellog',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='parcels.parcel'),
        ),
        migrations.AddField(
            model_name='parcellog',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='parcelpickup',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_pickups', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='parcelpickup',
            name='parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_event', to='parcels.parcel'),
        ),
        migrations.AddField(
            model_name='parcelpickup',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='parcels.parcel'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
    ]
