# Generated by Django 5.1.7 on 2025-12-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('pickup_station', 'Pickup Station'), ('hub', 'Transit Hub'), ('office', 'Company Office'), ('custom', 'Custom Location')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.location')),
                ('capacity', models.IntegerField(default=0)),
                ('operating_hours', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('connected_routes', models.TextField(blank=True)),
                ('vehicle_parking_capacity', models.IntegerField(default=0)),
            ],
            bases=('locations.location',),
        ),
        migrations.CreateModel(
            name='PickupStation',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.location')),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('max_storage_days', models.IntegerField(default=7)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('has_lockers', models.BooleanField(default=False)),
            ],
            bases=('locations.location',),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.location')),
                ('capacity', models.IntegerField(default=0)),
                ('has_cold_storage', models.BooleanField(default=False)),
                ('operating_hours', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
            ],
            bases=('locations.location',),
        ),
    ]
