# Generated by Django 5.1.7 on 2025-12-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='locations', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='hub',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='locations.location'),
        ),
        migrations.AddField(
            model_name='hub',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hubs', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='pickupstation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_location', to='locations.location'),
        ),
        migrations.AddField(
            model_name='pickupstation',
            name='station_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stations', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_location', to='locations.location'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to='staff.staff'),
        ),
    ]
